### ISSUE TITLE
Database contribution #1

### ISSUE THREAD

**Issue by bheimbu** [sihellem/TER-UCE-DB#1]
Hi Simon,

when will database contribution #1 be available? I'm especially interested in all Termitinae related UCE sequences.

Cheers Bastian

**Comment by sihellem** [comment]
Hi Bastian,

Thanks for your interest in the termite UCEs! Contribution #1 will be made available once the reviewing process of the associated manuscript is completed, which should hopefully be soon.

Best,
Simon

**Comment by bheimbu** [comment]
Hi Simon,

thanks for your quick reply. Fingers crossed that the manuscript will be accepted soon.

Cheers Bastian

**Comment by bastianheimburger** [comment]
Hi Simon,

congrats to your nice paper. Could you please send me the pdf of the paper? My university doesn't subscribe anymore to Elsevier journals and Scihub has not yet included your paper in its database.

Cheers Bastian

**Comment by sihellem** [comment]
Hi Bastian,

The data has now been released on Dryad: [https://doi.org/10.5061/dryad.x0k6djhn0](https://doi.org/10.5061/dryad.x0k6djhn0)

Cheers,
Simon
